[project]
name = "jac-way"
version = "1.0.0"
description = "Jac client application: jac-way"
entry-point = "main.jac"

[dependencies.npm]
jac-client-node = "1.0.4"
"class-variance-authority" = "^0.7.1"
clsx = "^2.1.1"
"tailwind-merge" = "^3.5.0"
"tw-animate-css" = "^1.4.0"
"radix-ui" = "^1.4.3"
"@fontsource-variable/figtree" = "^5.2.10"
"@fontsource-variable/geist" = "*"
"@fontsource-variable/inter" = "*"
"@fontsource-variable/noto-sans" = "*"
"@fontsource-variable/nunito-sans" = "*"
"@fontsource-variable/roboto" = "*"
"@fontsource-variable/raleway" = "*"
"@fontsource-variable/dm-sans" = "*"
"@fontsource-variable/public-sans" = "*"
"@fontsource-variable/outfit" = "*"
"@fontsource-variable/jetbrains-mono" = "*"
"@fontsource-variable/geist-mono" = "*"
"@hugeicons/core-free-icons" = "^3.1.1"
"@hugeicons/react" = "^1.1.5"
"@base-ui/react" = "^1.2.0"
shadcn = "^3.8.5"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"
"@tailwindcss/vite" = "latest"
tailwindcss = "latest"

[dev-dependencies]
watchdog = ">=3.0.0"

[serve]
base_route_app = "app"

[plugins.client.vite]
plugins = ["tailwindcss()"]
lib_imports = ["import tailwindcss from '@tailwindcss/vite'"]


[plugins.client.configs.tailwind]
# Generates tailwind.config.js
content = ["./src/**/*.{jac,tsx,jsx}"]